const A='public/staff/',SB=window.SUPABASE_CONFIG||{},cloudEnabled=Boolean(SB.url&&SB.anonKey);
const T={
th:{title:'ระบบข้อมูลพนักงานขับเครื่องจักรหน้างาน',subtitle:'ตรวจสอบพนักงาน เครื่องจักร พื้นที่ทำงาน และเวลาทำงาน',search:'🔎 ค้นหาชื่อ เบอร์โทร หรือรหัสเครื่องจักร...',add:'＋ เพิ่มพนักงาน',calendar:'ปฏิทินพนักงาน',adminLogin:'เข้าสู่โหมดแอดมิน',adminLogout:'ออกจากโหมดแอดมิน',pinHelp:'กรอกรหัสแอดมิน 6 หลักเพื่อเพิ่ม แก้ไข หรือลบข้อมูล',unlock:'ปลดล็อก',wrongPin:'รหัสไม่ถูกต้อง',viewer:'โหมดผู้เข้าชม — ดูข้อมูลได้อย่างเดียว',adminMode:'โหมดแอดมิน — สามารถจัดการข้อมูลได้',onlyOt:'เฉพาะคนทำ OT',onlyBroken:'เฉพาะเครื่องจักรเสีย',footer:'ระบบข้อมูลพนักงานขับเครื่องจักรหน้างาน · ซิงก์ข้อมูลผ่าน Supabase',allAreas:'ทุกพื้นที่',area:'พื้นที่',people:'คน',allTypes:'ทุกประเภท',allCompanies:'ทุกบริษัท',total:'พนักงานทั้งหมด',f2:'เครื่องจักรพื้นที่ F2',yard:'Stone Yard 3',workingCount:'กำลังทำงาน',otCount:'มีเวลา OT',stopped:'เสีย / หยุดงาน',items:'รายการ',duty:'หน้าที่',company:'สังกัด',call:'โทร',edit:'แก้ไข',delete:'ลบ',details:'รายละเอียด',noOt:'ไม่มี OT',empty:'ไม่พบข้อมูลที่ค้นหา',emptySub:'ลองเปลี่ยนคำค้นหาหรือตัวกรอง',addTitle:'เพิ่มข้อมูลพนักงาน',editTitle:'แก้ไขข้อมูล',upload:'📷 แตะเพื่ออัปโหลดรูปภาพ',cancel:'ยกเลิก',save:'บันทึกข้อมูล',phone:'เบอร์โทร',workArea:'พื้นที่ทำงาน',machine:'ประเภทเครื่องจักร',code:'รหัสเครื่องจักร',name:'ชื่อพนักงาน',start:'เวลาเริ่มงาน',end:'เวลาเลิกงาน',note:'หมายเหตุ',status:'สถานะ',workDate:'วันที่ทำงาน',otPeriods:'ช่วงเวลา OT (สูงสุด 3 ช่วง)',addOt:'＋ เพิ่มช่วง OT',confirmDelete:'ยืนยันลบพนักงานคนนี้?',today:'วันนี้',scheduled:'พนักงานประจำวัน',noSchedule:'ไม่มีพนักงานในวันนี้'},
en:{title:'Construction Site Machine Operator System',subtitle:'Check operators, machines, work areas and working hours',search:'🔎 Search name, phone or machine ID...',add:'＋ Add employee',calendar:'Employee calendar',adminLogin:'Admin login',adminLogout:'Exit admin mode',pinHelp:'Enter the 6-digit admin PIN to add, edit or delete records',unlock:'Unlock',wrongPin:'Incorrect PIN',viewer:'Visitor mode — view only',adminMode:'Admin mode — data management enabled',onlyOt:'OT only',onlyBroken:'Broken machines only',footer:'Machine Operator System · Synced with Supabase',allAreas:'All areas',area:'Area',people:'people',allTypes:'All types',allCompanies:'All companies',total:'Total employees',f2:'Machines in F2',yard:'Stone Yard 3',workingCount:'Working now',otCount:'With overtime',stopped:'Broken / stopped',items:'items',duty:'Duty',company:'Company',call:'Call',edit:'Edit',delete:'Delete',details:'Details',noOt:'No OT',empty:'No matching records',emptySub:'Try changing your search or filters',addTitle:'Add employee',editTitle:'Edit employee',upload:'📷 Tap to upload a photo',cancel:'Cancel',save:'Save',phone:'Phone',workArea:'Work area',machine:'Machine type',code:'Machine ID',name:'Employee name',start:'Start time',end:'End time',note:'Notes',status:'Status',workDate:'Work date',otPeriods:'OT periods (maximum 3)',addOt:'＋ Add OT period',confirmDelete:'Delete this employee?',today:'Today',scheduled:'Employees scheduled',noSchedule:'No employees scheduled'},
zh:{title:'施工现场机械操作员信息系统',subtitle:'查看操作员、机械、工作区域和工作时间',search:'🔎 搜索姓名、电话或机械编号...',add:'＋ 添加员工',calendar:'员工日历',adminLogin:'管理员登录',adminLogout:'退出管理员模式',pinHelp:'请输入6位管理员密码以添加、编辑或删除资料',unlock:'解锁',wrongPin:'密码不正确',viewer:'访客模式 — 仅可查看',adminMode:'管理员模式 — 可管理资料',onlyOt:'仅显示加班人员',onlyBroken:'仅显示故障机械',footer:'机械操作员信息系统 · 已同步 Supabase',allAreas:'全部区域',area:'区域',people:'人',allTypes:'全部类型',allCompanies:'全部公司',total:'员工总数',f2:'F2 区机械',yard:'Stone Yard 3',workingCount:'正在工作',otCount:'有加班',stopped:'故障 / 停工',items:'项',duty:'职责',company:'公司',call:'拨打',edit:'编辑',delete:'删除',details:'详情',noOt:'无加班',empty:'未找到相关记录',emptySub:'请更改搜索词或筛选条件',addTitle:'添加员工',editTitle:'编辑员工',upload:'📷 点击上传照片',cancel:'取消',save:'保存',phone:'电话',workArea:'工作区域',machine:'机械类型',code:'机械编号',name:'员工姓名',start:'上班时间',end:'下班时间',note:'备注',status:'状态',workDate:'工作日期',otPeriods:'加班时段（最多3段）',addOt:'＋ 添加加班时段',confirmDelete:'确认删除此员工？',today:'今天',scheduled:'当天员工',noSchedule:'当天没有员工'}
};
const STATUS={working:{th:'กำลังทำงาน',en:'Working',zh:'工作中'},break:{th:'พัก',en:'Break',zh:'休息'},waiting:{th:'รอคำสั่ง',en:'Waiting',zh:'等待指令'},broken:{th:'เครื่องจักรเสีย',en:'Machine broken',zh:'机械故障'},finished:{th:'เลิกงานแล้ว',en:'Finished',zh:'已下班'},ot:{th:'ทำ OT',en:'Overtime',zh:'加班中'}};
const types=['Bulldozer','Excavator','Grader','Roller'],areas=['F2','3 E0 Stone Yard 3'];
let data=[];try{data=JSON.parse(localStorage.getItem('operators-images-v2'))||[]}catch{};
let lang=localStorage.getItem('operator-lang')||'th',area='all',editing=null,image='',adminPin='',calendarDate=new Date(),pendingFile=null;
const savedAdminPin=sessionStorage.getItem('admin-pin')||'';
const $=id=>document.getElementById(id),tr=k=>T[lang][k]||k,esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const headers=()=>({'apikey':SB.anonKey,'Authorization':'Bearer '+SB.anonKey,'Content-Type':'application/json'});
async function request(path,options={}){let r=await fetch(SB.url+path,{...options,headers:{...headers(),...(options.headers||{})}}),text=await r.text();if(!r.ok)throw new Error(text);return text?JSON.parse(text):null}
const fromRow=x=>({id:Number(x.id),name:x.name,phone:x.phone,company:x.company,area:x.area,type:x.type,code:x.code,job:x.job||'',status:x.status,image:x.image||A+'image-1.png',start:x.start_time||'07:00',end:x.end_time||'17:00',otSlots:Array.isArray(x.ot_slots)?x.ot_slots:(x.ot_start?[{start:x.ot_start,end:x.ot_end}]:[]),workDate:x.work_date||new Date().toISOString().slice(0,10),note:x.note||''});
const toRow=x=>({id:x.id,name:x.name,phone:x.phone,company:x.company,area:x.area,type:x.type,code:x.code,job:x.job||'',status:x.status,image:x.image||'',start_time:x.start||'',end_time:x.end||'',ot_slots:x.otSlots||[],work_date:x.workDate,note:x.note||''});
function saveLocal(){localStorage.setItem('operators-images-v2',JSON.stringify(data))}
async function syncCloud(){if(!cloudEnabled)return;try{let rows=await request('/rest/v1/machine_operators?select=*&order=id.asc');data=rows.map(fromRow);saveLocal();render()}catch(e){console.warn('Supabase sync:',e.message)}}
async function checkPin(pin){try{return await request('/rest/v1/rpc/admin_check',{method:'POST',body:JSON.stringify({p_pin:pin})})===true}catch{return false}}
async function saveCloud(item){await request('/rest/v1/rpc/admin_upsert_operator',{method:'POST',body:JSON.stringify({p_pin:adminPin,p_operator:toRow(item)})})}
async function deleteCloud(id){await request('/rest/v1/rpc/admin_delete_operator',{method:'POST',body:JSON.stringify({p_pin:adminPin,p_id:id})})}
function isAdmin(){return adminPin.length===6}
function applyLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(x=>x.textContent=tr(x.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(x=>x.placeholder=tr(x.dataset.i18nPlaceholder));document.querySelectorAll('[data-lang]').forEach(x=>x.classList.toggle('active',x.dataset.lang===lang));$('date').textContent=new Intl.DateTimeFormat(lang==='th'?'th-TH':lang==='zh'?'zh-CN':'en-GB',{dateStyle:'long'}).format(new Date());updateAdminUI();render()}
function updateAdminUI(){$('addButton').hidden=!isAdmin();$('addButton').textContent=tr('add');$('adminButton').textContent=isAdmin()?'🔒 '+tr('adminLogout'):'🔑 '+tr('adminLogin');$('calendarButton').textContent='📅 '+tr('calendar');$('adminNotice').className='admin-notice '+(isAdmin()?'admin-on':'');$('adminNotice').textContent=isAdmin()?'✓ '+tr('adminMode'):'👁 '+tr('viewer')}
function options(a,v){return a.map(x=>`<option ${x===v?'selected':''}>${esc(x)}</option>`).join('')}
function render(){let q=$('search').value.toLowerCase(),type=$('type').value,company=$('company').value;if(!types.includes(type))type=tr('allTypes');if(!data.some(x=>x.company===company))company=tr('allCompanies');let list=data.filter(x=>(area==='all'||x.area===area)&&(type===tr('allTypes')||x.type===type)&&(company===tr('allCompanies')||x.company===company)&&(!$('ot').checked||x.otSlots?.length)&&(!$('broken').checked||x.status==='broken')&&(!q||[x.name,x.phone,x.code].some(v=>v.toLowerCase().includes(q))));
$('type').innerHTML=options([tr('allTypes'),...types],type);$('company').innerHTML=options([tr('allCompanies'),...new Set(data.map(x=>x.company))],company);
$('stats').innerHTML=[[tr('total'),data.length],[tr('f2'),data.filter(x=>x.area==='F2').length],[tr('yard'),data.filter(x=>x.area!=='F2').length],[tr('workingCount'),data.filter(x=>['working','ot'].includes(x.status)).length],[tr('otCount'),data.filter(x=>x.otSlots?.length).length],[tr('stopped'),data.filter(x=>x.status==='broken').length]].map(([l,n])=>`<div class="stat">■<b>${n}</b><small>${l}</small></div>`).join('');
$('tabs').innerHTML=[['all',tr('allAreas')],...areas.map(x=>[x,tr('area')+' '+x])].map(([v,l])=>`<button class="tab ${area===v?'active':''}" data-area="${v}">${l} · ${v==='all'?data.length:data.filter(y=>y.area===v).length} ${tr('people')}</button>`).join('');
$('content').innerHTML=types.map(t=>{let items=list.filter(x=>x.type===t);return items.length?`<section class="section"><div class="section-head"><h2>${t}</h2><span class="count">${items.length} ${tr('items')}</span></div><div class="grid">${items.map(card).join('')}</div></section>`:''}).join('')||`<div class="empty"><h3>${tr('empty')}</h3><p>${tr('emptySub')}</p></div>`;bindUI()}
function otText(x){return x.otSlots?.length?x.otSlots.map(o=>`${o.start}–${o.end}`).join(', '):tr('noOt')}
function card(x){return `<article class="card"><div class="photo"><img src="${x.image}" alt="${esc(x.name)}" loading="lazy"><div class="shade"></div><span class="badge type">${x.type}</span><span class="badge status ${x.status}">${STATUS[x.status][lang]}</span><div class="info"><h3>${esc(x.name)}</h3><p>📍 ${esc(x.area)} · ${esc(x.code)}</p><div class="times"><span>◷ ${x.start}–${x.end}</span><span>OT ${esc(otText(x))}</span></div></div></div><div class="meta"><div class="meta-row"><div><small>${tr('duty')}</small>${esc(x.job)}</div><div><small>${tr('workDate')}</small>${esc(x.workDate)}</div></div><div class="actions ${isAdmin()?'admin-actions':''}"><a class="call" href="tel:${x.phone}">☎ ${tr('call')}</a>${isAdmin()?`<button class="edit" data-edit="${x.id}">✎ ${tr('edit')}</button><button class="delete" data-delete="${x.id}">⌫ ${tr('delete')}</button>`:''}<button class="detail" data-detail="${x.id}">◉ ${tr('details')}</button></div></div></article>`}
function bindUI(){document.querySelectorAll('[data-area]').forEach(x=>x.onclick=()=>{area=x.dataset.area;render()});document.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>openForm(+x.dataset.edit));document.querySelectorAll('[data-detail]').forEach(x=>x.onclick=()=>openDetail(+x.dataset.detail));document.querySelectorAll('[data-delete]').forEach(x=>x.onclick=()=>removeEmployee(+x.dataset.delete))}
function openAdmin(){$('pinInput').value='';$('pinError').textContent='';$('adminModal').classList.add('open');$('pinInput').focus()}
$('adminForm').onsubmit=async e=>{e.preventDefault();let pin=$('pinInput').value,ok=await checkPin(pin);if(!ok){$('pinError').textContent=tr('wrongPin');return}adminPin=pin;sessionStorage.setItem('admin-pin',pin);$('adminModal').classList.remove('open');updateAdminUI();render()};
function openForm(id){if(!isAdmin())return openAdmin();editing=data.find(x=>x.id===id)||null;let v=editing||{area:'F2',type:'Bulldozer',status:'working',start:'07:00',end:'17:00',workDate:new Date().toISOString().slice(0,10),otSlots:[]};image=v.image||'';pendingFile=null;$('formTitle').textContent=editing?tr('editTitle'):tr('addTitle');$('previewText').textContent=tr('upload');$('fields').innerHTML=formFields(v);$('formModal').classList.add('open');showPreview();bindOt()}
function formFields(v){let input=(k,l,t='text',req='')=>`<div class="field"><label>${tr(l)}</label><input name="${k}" type="${t}" value="${esc(v[k]||'')}" ${req}></div>`;return input('name','name','text','required')+input('phone','phone','tel','required')+input('company','company','text','required')+`<div class="field"><label>${tr('workArea')}</label><select name="area">${options(areas,v.area)}</select></div><div class="field"><label>${tr('machine')}</label><select name="type">${options(types,v.type)}</select></div>`+input('code','code','text','required')+input('job','duty')+`<div class="field"><label>${tr('status')}</label><select name="status">${Object.entries(STATUS).map(([k,l])=>`<option value="${k}" ${v.status===k?'selected':''}>${l[lang]}</option>`).join('')}</select></div>`+input('start','start','time')+input('end','end','time')+input('workDate','workDate','date')+input('note','note')+`<div class="ot-field"><label>${tr('otPeriods')}</label><div id="otRows">${(v.otSlots||[]).slice(0,3).map(otRow).join('')}</div><button type="button" id="addOt" class="ghost-light">${tr('addOt')}</button></div><div class="form-actions"><button type="button" class="cancel" data-close="formModal">${tr('cancel')}</button><button class="save">${tr('save')}</button></div>`}
function otRow(o={start:'',end:''}){return `<div class="ot-row"><input type="time" data-ot-start value="${o.start||''}"><span>–</span><input type="time" data-ot-end value="${o.end||''}"><button type="button" data-remove-ot>✕</button></div>`}
function bindOt(){$('addOt').onclick=()=>{if(document.querySelectorAll('.ot-row').length<3){$('otRows').insertAdjacentHTML('beforeend',otRow());bindOt()}};document.querySelectorAll('[data-remove-ot]').forEach(x=>x.onclick=()=>x.closest('.ot-row').remove());document.querySelectorAll('[data-close]').forEach(bindClose)}
function showPreview(){$('preview').hidden=!image;$('previewText').hidden=!!image;if(image)$('preview').src=image}
$('photo').onchange=e=>{pendingFile=e.target.files[0]||null;if(pendingFile){let r=new FileReader();r.onload=()=>{image=r.result;showPreview()};r.readAsDataURL(pendingFile)}};
$('form').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target).entries());v.id=editing?editing.id:Date.now();v.image=image||A+'image-1.png';v.otSlots=[...document.querySelectorAll('.ot-row')].map(r=>({start:r.querySelector('[data-ot-start]').value,end:r.querySelector('[data-ot-end]').value})).filter(x=>x.start&&x.end).slice(0,3);try{await saveCloud(v);data=editing?data.map(x=>x.id===v.id?v:x):[v,...data];saveLocal();$('formModal').classList.remove('open');render()}catch{adminPin='';sessionStorage.removeItem('admin-pin');$('formModal').classList.remove('open');updateAdminUI();render();openAdmin();$('pinError').textContent=tr('wrongPin')}};
async function removeEmployee(id){if(!isAdmin())return openAdmin();if(!confirm(tr('confirmDelete')))return;try{await deleteCloud(id);data=data.filter(x=>x.id!==id);saveLocal();render()}catch{adminPin='';sessionStorage.removeItem('admin-pin');updateAdminUI();openAdmin()}}
function openDetail(id){let x=data.find(x=>x.id===id);$('detailTitle').textContent=x.name;$('detailBody').innerHTML=`<img class="detail-img" src="${x.image}"><div class="detail-grid">${[[tr('phone'),x.phone],[tr('company'),x.company],[tr('workArea'),x.area],[tr('machine'),x.type+' · '+x.code],[tr('duty'),x.job],[tr('start'),x.start+'–'+x.end],['OT',otText(x)],[tr('workDate'),x.workDate],[tr('status'),STATUS[x.status][lang]]].map(a=>`<div><small>${a[0]}</small><br><b>${esc(a[1])}</b></div>`).join('')}</div><a class="call detail-call" href="tel:${x.phone}">☎ ${tr('call')} ${x.phone}</a>`;$('detailModal').classList.add('open')}
function renderCalendar(){let y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=first.getDay();$('calendarTitle').textContent=new Intl.DateTimeFormat(lang==='th'?'th-TH':lang==='zh'?'zh-CN':'en-GB',{month:'long',year:'numeric'}).format(first);$('calendarWeek').innerHTML=(lang==='th'?['อา','จ','อ','พ','พฤ','ศ','ส']:lang==='zh'?['日','一','二','三','四','五','六']:['Sun','Mon','Tue','Wed','Thu','Fri','Sat']).map(x=>`<b>${x}</b>`).join('');let html='<span></span>'.repeat(offset);for(let d=1;d<=days;d++){let key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,n=data.filter(x=>x.workDate===key).length,today=key===new Date().toISOString().slice(0,10);html+=`<button data-cal-date="${key}" class="cal-day ${today?'today':''}"><b>${d}</b>${n?`<small>${n} ${tr('people')}</small>`:''}</button>`}$('calendarGrid').innerHTML=html;document.querySelectorAll('[data-cal-date]').forEach(x=>x.onclick=()=>showCalendarEmployees(x.dataset.calDate));showCalendarEmployees(new Date().toISOString().slice(0,10))}
function showCalendarEmployees(date){let list=data.filter(x=>x.workDate===date);$('calendarEmployees').innerHTML=`<h3>${tr('scheduled')} · ${date}</h3>`+(list.length?list.map(x=>`<div><img src="${x.image}"><span><b>${esc(x.name)}</b><small>${x.type} · ${x.start}–${x.end}${x.otSlots?.length?' · OT '+otText(x):''}</small></span></div>`).join(''):`<p>${tr('noSchedule')}</p>`)}
function bindClose(x){x.onclick=()=>x.closest('.modal').classList.remove('open')}
document.querySelectorAll('[data-close]').forEach(bindClose);$('addButton').onclick=()=>openForm();$('adminButton').onclick=()=>{if(isAdmin()){adminPin='';sessionStorage.removeItem('admin-pin');updateAdminUI();render()}else openAdmin()};$('calendarButton').onclick=()=>{$('calendarModal').classList.add('open');renderCalendar()};$('prevMonth').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar()};$('nextMonth').onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar()};document.querySelectorAll('[data-lang]').forEach(x=>x.onclick=()=>{lang=x.dataset.lang;localStorage.setItem('operator-lang',lang);applyLanguage()});['search','type','company','ot','broken'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));applyLanguage();syncCloud();(async()=>{if(savedAdminPin&&await checkPin(savedAdminPin)){adminPin=savedAdminPin;updateAdminUI();render()}else sessionStorage.removeItem('admin-pin')})();
