const A='public/staff/';
const I={
th:{title:'ระบบข้อมูลพนักงานขับเครื่องจักรหน้างาน',subtitle:'ตรวจสอบพนักงาน เครื่องจักร พื้นที่ทำงาน และเวลาทำงาน',add:'＋ เพิ่มข้อมูลพนักงาน',search:'🔎 ค้นหาชื่อ เบอร์โทร หรือรหัสเครื่องจักร...',onlyOt:'เฉพาะคนทำ OT',onlyBroken:'เฉพาะเครื่องจักรเสีย',footer:'ระบบข้อมูลพนักงานขับเครื่องจักรหน้างาน · ข้อมูลถูกบันทึกในอุปกรณ์นี้',allAreas:'ทุกพื้นที่',area:'พื้นที่',people:'คน',allTypes:'ทุกประเภท',allCompanies:'ทุกบริษัท',total:'พนักงานทั้งหมด',f2:'เครื่องจักรพื้นที่ F2',yard:'Stone Yard 3',workingCount:'กำลังทำงาน',otCount:'กำลังทำ OT',stopped:'เสีย / หยุดงาน',items:'รายการ',duty:'หน้าที่',company:'สังกัด',call:'โทร',edit:'แก้ไข',details:'รายละเอียด',noOt:'ไม่มี OT',empty:'ไม่พบข้อมูลที่ค้นหา',emptySub:'ลองเปลี่ยนคำค้นหาหรือตัวกรอง',addTitle:'เพิ่มข้อมูลพนักงาน',editTitle:'แก้ไขข้อมูล',upload:'📷 แตะเพื่ออัปโหลดรูปภาพ',cancel:'ยกเลิก',save:'บันทึกข้อมูล',phone:'เบอร์โทร',workArea:'พื้นที่ทำงาน',machine:'ประเภทเครื่องจักร',code:'รหัสเครื่องจักร',name:'ชื่อพนักงาน',start:'เวลาเริ่มงาน',end:'เวลาเลิกงาน',otStart:'เวลาเริ่ม OT',otEnd:'เวลาเลิก OT',note:'หมายเหตุ',status:'สถานะ',filterRock:'สำหรับกรองหิน'},
en:{title:'Construction Site Machine Operator System',subtitle:'Check operators, machines, work areas and working hours',add:'＋ Add employee',search:'🔎 Search name, phone or machine ID...',onlyOt:'OT only',onlyBroken:'Broken machines only',footer:'Machine Operator System · Data is stored on this device',allAreas:'All areas',area:'Area',people:'people',allTypes:'All types',allCompanies:'All companies',total:'Total employees',f2:'Machines in F2',yard:'Stone Yard 3',workingCount:'Working now',otCount:'On overtime',stopped:'Broken / stopped',items:'items',duty:'Duty',company:'Company',call:'Call',edit:'Edit',details:'Details',noOt:'No OT',empty:'No matching records',emptySub:'Try changing your search or filters',addTitle:'Add employee',editTitle:'Edit employee',upload:'📷 Tap to upload a photo',cancel:'Cancel',save:'Save',phone:'Phone',workArea:'Work area',machine:'Machine type',code:'Machine ID',name:'Employee name',start:'Start time',end:'End time',otStart:'OT start',otEnd:'OT end',note:'Notes',status:'Status',filterRock:'Rock screening'},
zh:{title:'施工现场机械操作员信息系统',subtitle:'查看操作员、机械、工作区域和工作时间',add:'＋ 添加员工',search:'🔎 搜索姓名、电话或机械编号...',onlyOt:'仅显示加班人员',onlyBroken:'仅显示故障机械',footer:'机械操作员信息系统 · 数据保存在此设备上',allAreas:'全部区域',area:'区域',people:'人',allTypes:'全部类型',allCompanies:'全部公司',total:'员工总数',f2:'F2 区机械',yard:'Stone Yard 3',workingCount:'正在工作',otCount:'正在加班',stopped:'故障 / 停工',items:'项',duty:'职责',company:'公司',call:'拨打',edit:'编辑',details:'详情',noOt:'无加班',empty:'未找到相关记录',emptySub:'请更改搜索词或筛选条件',addTitle:'添加员工',editTitle:'编辑员工',upload:'📷 点击上传照片',cancel:'取消',save:'保存',phone:'电话',workArea:'工作区域',machine:'机械类型',code:'机械编号',name:'员工姓名',start:'上班时间',end:'下班时间',otStart:'加班开始',otEnd:'加班结束',note:'备注',status:'工作状态',filterRock:'石料筛选'}
};
const S={working:{th:'กำลังทำงาน',en:'Working',zh:'工作中'},break:{th:'พัก',en:'Break',zh:'休息'},waiting:{th:'รอคำสั่ง',en:'Waiting',zh:'等待指令'},broken:{th:'เครื่องจักรเสีย',en:'Machine broken',zh:'机械故障'},finished:{th:'เลิกงานแล้ว',en:'Finished',zh:'已下班'},ot:{th:'ทำ OT',en:'Overtime',zh:'加班中'}};
const names=['สมชาย ใจดี','ประสิทธิ์ มั่นคง','วิชัย แสงทอง','สุชาติ พูนผล','อนันต์ ภักดี','ณรงค์ ชัยชนะ','กิตติศักดิ์ บุญมี','มานพ ใจกล้า','วีระพล ขยันงาน','ชาญชัย กล้าหาญ','ธนวัฒน์ คงดี','อาทิตย์ รุ่งเรือง','บุญส่ง แก้วใส','จักรพันธ์ มั่นใจ','สมศักดิ์ มีสุข','ปรีชา งานดี','วัฒนา พึ่งตน','ชัยวัฒน์ แสนดี','รณชัย ใจสู้'];
const types=['Bulldozer','Excavator','Grader','Roller'],areas=['F2','3 E0 Stone Yard 3'],companies=['BOOM Construction','PST Heavy Machine','Siam Compact','Stone Yard Service'];
const seed=names.map((name,i)=>{let type=types[i%4],area=i<12?'F2':'3 E0 Stone Yard 3',status=['working','working','ot','break','waiting','working','broken','finished'][i%8];return{id:i+1,name,phone:'08'+String(12457788+i*7319).slice(-8),company:companies[i%4],area,type,code:type.slice(0,2).toUpperCase()+'-'+(area==='F2'?'F2':'E0')+'-'+String(i+1).padStart(2,'0'),job:type==='Bulldozer'?'ปรับระดับและดันดิน':type==='Excavator'?(area==='F2'?'ขุดและตักดิน':'กรองและคัดแยกหิน'):type==='Grader'?'เกลี่ยพื้นที่':'บดอัดพื้นที่',status,image:A+'image-'+(i+1)+'.png',start:'07:00',end:'17:00',otStart:status==='ot'?'17:30':'',otEnd:status==='ot'?'20:00':'',note:''}});
let data;try{data=JSON.parse(localStorage.getItem('operators-images-v2'))||seed}catch(e){data=seed}if(data.length<19)data=seed;
const SB=window.SUPABASE_CONFIG||{},cloudEnabled=Boolean(SB.url&&SB.anonKey);
const cloudHeaders=()=>({'apikey':SB.anonKey,'Authorization':'Bearer '+SB.anonKey,'Content-Type':'application/json'});
const toRow=x=>({id:x.id,name:x.name,phone:x.phone,company:x.company,area:x.area,type:x.type,code:x.code,job:x.job||'',status:x.status,image:x.image||'',start_time:x.start||'',end_time:x.end||'',ot_start:x.otStart||'',ot_end:x.otEnd||'',note:x.note||''});
const fromRow=x=>({id:Number(x.id),name:x.name,phone:x.phone,company:x.company,area:x.area,type:x.type,code:x.code,job:x.job||'',status:x.status,image:x.image||'',start:x.start_time||'',end:x.end_time||'',otStart:x.ot_start||'',otEnd:x.ot_end||'',note:x.note||''});
async function cloudRequest(path,options={}){let response=await fetch(SB.url+path,{...options,headers:{...cloudHeaders(),...(options.headers||{})}}),text=await response.text();if(!response.ok)throw new Error(text);return text?JSON.parse(text):null}
async function syncCloud(){if(!cloudEnabled)return;try{let rows=await cloudRequest('/rest/v1/machine_operators?select=*&order=id.asc');if(!rows.length){await cloudRequest('/rest/v1/machine_operators',{method:'POST',headers:{'Prefer':'resolution=merge-duplicates'},body:JSON.stringify(seed.map(toRow))});rows=seed.map(toRow)}data=rows.map(fromRow);save();render()}catch(error){console.warn('Supabase sync:',error.message)}}
async function saveCloud(item){if(!cloudEnabled)return;try{await cloudRequest('/rest/v1/machine_operators?on_conflict=id',{method:'POST',headers:{'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(toRow(item))})}catch(error){console.warn('Supabase save:',error.message)}}
let lang=localStorage.getItem('operator-lang')||'th',area='all',editing=null,image='';const $=id=>document.getElementById(id),tr=k=>I[lang][k]||k,esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('operators-images-v2',JSON.stringify(data))}function options(a,val){return a.map(x=>`<option ${x===val?'selected':''}>${esc(x)}</option>`).join('')}
function applyLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(x=>x.textContent=tr(x.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(x=>x.placeholder=tr(x.dataset.i18nPlaceholder));document.querySelectorAll('[data-lang]').forEach(x=>x.classList.toggle('active',x.dataset.lang===lang));$('date').textContent=new Intl.DateTimeFormat(lang==='th'?'th-TH':lang==='zh'?'zh-CN':'en-GB',{dateStyle:'long'}).format(new Date());render()}
function render(){let q=$('search').value.toLowerCase(),type=$('type').value,company=$('company').value;if(!types.includes(type))type=tr('allTypes');if(!data.some(x=>x.company===company))company=tr('allCompanies');let list=data.filter(x=>(area==='all'||x.area===area)&&(type===tr('allTypes')||x.type===type)&&(company===tr('allCompanies')||x.company===company)&&(!$('ot').checked||x.status==='ot')&&(!$('broken').checked||x.status==='broken')&&(!q||[x.name,x.phone,x.code].some(v=>v.toLowerCase().includes(q))));
$('type').innerHTML=options([tr('allTypes'),...types],type);let cs=[...new Set(data.map(x=>x.company))];$('company').innerHTML=options([tr('allCompanies'),...cs],company);
$('stats').innerHTML=[[tr('total'),data.length],[tr('f2'),data.filter(x=>x.area==='F2').length],[tr('yard'),data.filter(x=>x.area!=='F2').length],[tr('workingCount'),data.filter(x=>['working','ot'].includes(x.status)).length],[tr('otCount'),data.filter(x=>x.status==='ot').length],[tr('stopped'),data.filter(x=>x.status==='broken').length]].map(([l,n])=>`<div class="stat">◼<b>${n}</b><small>${l}</small></div>`).join('');
$('tabs').innerHTML=[['all',tr('allAreas')],...areas.map(x=>[x,tr('area')+' '+x])].map(([v,l])=>`<button class="tab ${area===v?'active':''}" data-area="${v}">${l} · ${v==='all'?data.length:data.filter(y=>y.area===v).length} ${tr('people')}</button>`).join('');document.querySelectorAll('[data-area]').forEach(x=>x.onclick=()=>{area=x.dataset.area;render()});
$('content').innerHTML=types.map(t=>{let items=list.filter(x=>x.type===t);return items.length?`<section class="section"><div class="section-head"><h2>${t}${area.includes('Stone')&&t==='Excavator'?' — '+tr('filterRock'):''}</h2><span class="count">${items.length} ${tr('items')}</span></div><div class="grid">${items.map(card).join('')}</div></section>`:''}).join('')||`<div class="empty"><h3>${tr('empty')}</h3><p>${tr('emptySub')}</p></div>`}
function card(x){return `<article class="card"><div class="photo"><img src="${x.image}" alt="${esc(x.name)}" loading="lazy"><div class="shade"></div><span class="badge type">${x.type}</span><span class="badge status ${x.status}">${S[x.status][lang]}</span><div class="info"><h3>${esc(x.name)}</h3><p>📍 ${esc(x.area)} · ${esc(x.code)}</p><div class="times"><span>◷ ${x.start}–${x.end}</span><span>${x.otStart?'OT '+x.otStart+'–'+x.otEnd:tr('noOt')}</span></div></div></div><div class="meta"><div class="meta-row"><div><small>${tr('duty')}</small>${esc(x.job)}</div><div><small>${tr('company')}</small>${esc(x.company)}</div></div><div class="actions"><a class="call" href="tel:${x.phone}">☎ ${tr('call')}</a><button class="edit" data-edit="${x.id}">✎ ${tr('edit')}</button><button class="detail" data-detail="${x.id}">◉ ${tr('details')}</button></div></div></article>`}
function bindCards(){document.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>openForm(+x.dataset.edit));document.querySelectorAll('[data-detail]').forEach(x=>x.onclick=()=>openDetail(+x.dataset.detail))}new MutationObserver(bindCards).observe($('content'),{childList:true});
const fieldDefs=[['name','name','text'],['phone','phone','tel'],['company','company','text'],['area','workArea','area'],['type','machine','type'],['code','code','text'],['job','duty','text'],['status','status','status'],['start','start','time'],['end','end','time'],['otStart','otStart','time'],['otEnd','otEnd','time'],['note','note','text']];
function openForm(id){editing=data.find(x=>x.id===id)||null;let v=editing||{area:'F2',type:'Bulldozer',status:'working',start:'07:00',end:'17:00'};image=v.image||'';$('formTitle').textContent=editing?tr('editTitle'):tr('addTitle');$('previewText').textContent=tr('upload');$('fields').innerHTML=fieldDefs.map(([key,label,kind])=>`<div class="field"><label>${tr(label)}</label>${kind==='area'?`<select name="area">${options(areas,v.area)}</select>`:kind==='type'?`<select name="type">${options(types,v.type)}</select>`:kind==='status'?`<select name="status">${Object.entries(S).map(([k,l])=>`<option value="${k}" ${v.status===k?'selected':''}>${l[lang]}</option>`).join('')}</select>`:`<input name="${key}" type="${kind}" value="${esc(v[key]||'')}" ${['name','phone','company','code'].includes(key)?'required':''}>`}</div>`).join('')+`<div class="form-actions"><button type="button" class="cancel" id="cancelButton">${tr('cancel')}</button><button class="save">${tr('save')}</button></div>`;$('cancelButton').onclick=closeForm;showPreview();$('formModal').classList.add('open')}
function showPreview(){$('preview').hidden=!image;$('previewText').hidden=!!image;if(image)$('preview').src=image}function closeForm(){$('formModal').classList.remove('open')}
$('photo').onchange=e=>{let f=e.target.files[0];if(f){let r=new FileReader;r.onload=()=>{image=r.result;showPreview()};r.readAsDataURL(f)}};$('form').onsubmit=async e=>{e.preventDefault();let v=Object.fromEntries(new FormData(e.target).entries());v.image=image||A+'image-1.png';v.id=editing?editing.id:Date.now();data=editing?data.map(x=>x.id===v.id?v:x):[v,...data];save();closeForm();render();await saveCloud(v)};
function openDetail(id){let x=data.find(x=>x.id===id);$('detailTitle').textContent=x.name;$('detailBody').innerHTML=`<img class="detail-img" src="${x.image}" alt="${esc(x.name)}"><div class="detail-grid">${[[tr('phone'),x.phone],[tr('company'),x.company],[tr('workArea'),x.area],[tr('machine'),x.type+' · '+x.code],[tr('duty'),x.job],[tr('start'),x.start+'–'+x.end],[tr('otStart'),x.otStart?x.otStart+'–'+x.otEnd:'—'],[tr('status'),S[x.status][lang]]].map(a=>`<div><small>${a[0]}</small><br><b>${esc(a[1])}</b></div>`).join('')}</div><a class="call detail-call" href="tel:${x.phone}">☎ ${tr('call')} ${x.phone}</a>`;$('detailModal').classList.add('open')}
function closeDetail(){$('detailModal').classList.remove('open')}
$('addButton').onclick=()=>openForm();$('formClose').onclick=closeForm;$('detailClose').onclick=closeDetail;document.querySelectorAll('[data-lang]').forEach(x=>x.onclick=()=>{lang=x.dataset.lang;localStorage.setItem('operator-lang',lang);applyLanguage()});['search','type','company','ot','broken'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));applyLanguage();syncCloud();
